### ISSUE TITLE
Link to online version of my portfolio

### ISSUE THREAD

**Issue by Zeph180** [Zeph180/my-portfolio-microverse#8]
The site is available online at www.kigozijosephsuubi.me
Add link to my portfolio on the deployment branch

**Comment by jerryowusu** [comment]
Hi @Zeph180 , 

Good job so far!
Your project is looking fantastic so far :star_struck: 

However, there are few changes you need to make in order to move on to the next level :sunglasses:

![almost-there-reach](https://user-images.githubusercontent.com/65233860/208468405-9b090760-42f3-465a-97b9-45a71905f01b.gif)


## Highlights
Great effort on this milestone :heavy_check_mark: 
Nice using the new issues page :heavy_check_mark: 

## Required Changes ♻️

- [ ] Kindly update your readme file with the link to the website since it is part of the project requirements. :wink: 

_Check the comments under the review._

## Optional suggestions

- [ ] Your readme file is not up to standard since most of the header/sections of the microvers readme template are missing. Kindly ensure that all headers/sections including the Future Features are presented and updated according to your credentials :+1: 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Zeph180** [comment]
@jerryowusu  
Thank you for the feedback.
But just for clarity's sake should I create another issue or submit this every one for a review after making the changes

**Comment by franclobo** [comment]
Hi @Zeph180, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- The link works as expected ✔️ 

## Optional suggestions

- [ ] **[OPTIONAL]** I suggest adding the LIVE DEMO section to your README file to paste the portfolio's link, it is easier to the user find the link 👇🏽 

![image](https://user-images.githubusercontent.com/58642949/208488758-d51db457-8b9e-464f-aeb8-814ee1362c2c.png)


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
